spring:
  datasource:
    username: root
    password: mysql.
    url: jdbc:mysql://hxwl:3306/gulimall_ums
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: hxwl:8848
  application:
    name: gulimall-member
  redis:
    host: hxwl
    port: 6379

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto  # 自增主键
  session:
    store-type: redis
server:
  port: 8000
  servlet:
    session:
      timeout: 30m
