spring:
  application:
    name: gulimall-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: hxwl:8848
  thymeleaf:
    cache: false
  redis:
    host: hxwl
    port: 6379
  session:
    store-type: redis


server:
  port: 20000
  servlet:
    session:
      timeout: 30m