spring:
  cloud:
    gateway:
      routes:
        - id: test_route
          uri: http://www.baidu.com
          predicates:
            - Query=url,baidu

        - id: qq_route
          uri: http://huoxinwl.cn
          predicates:
            - Query=url,qq