spring:
  cloud:
    nacos:
      discovery:
        server-addr: hxwl:8848
    alicloud:
      access-key: LTAI5tMCpYpA7PcfTX6XrSj2
      secret-key: rg6hUM46wYFhTJO4FWJuoxDIS169HX
      oss:
        endpoint: oss-cn-shenzhen.aliyuncs.com
        bucket: gulimall-huoxin
      # 短信验证码
      sms:
        host: https://fesms.market.alicloudapi.com
        path: /sms/
        skin: 1
        sign: 175622
        appcode: b0563c23aff8428c97a54d4f7f9e28e5

  application:
    name: gulimall-third-party

server:
  port: 30000